# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: REScala
email: salvaneschi@st.informatik.tu-darmstadt.de
description: > # this means to ignore newlines until "baseurl:"
  REScala is a reactive language which integrates concepts from event-based and functional-reactive programming into the object-oriented world.
baseurl: "" # the subpath of your site, e.g. /blog

relative_links:
  enabled: false

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

markdown: kramdown

# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input:              GFM
  parse_block_html:   true # parse markdown commands inside <div> blocks
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

repository: -rescala-lang/REScala
