title: REScala
email: mezini@st.informatik.tu-darmstadt.de
description: >- # this means to ignore newlines until "baseurl:"
  REScala is the most advanced solution for functional reactive programming on the JVM and the Web.
baseurl: "/"
url: "https://www.rescala-lang.com/"
twitter_username: stg_darmstadt
github_username: rescala-lang

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  parse_html: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

plugins:
  - jekyll-feed

collections:
  publications:
    output: false
  showcases:
    output: false

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
